config/routes.rb
Rails.application.routes.draw do
  get "/" => "welcome#index"
  get "/quotes" => "quotes#index"
  post "/create_quote" => "quotes#create"
  get "/quotes/:id" => "quotes#show", as: :show_quote
  delete "/quotes/:id" => "quotes#delete", as: :delete_quote

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def create
    quote_params = get_quote.body
    Quote.create(quote_params)
    redirect_to quotes_path
  end

  def show
    @quote = Quote.find(params[:id])
  end
  
  def delete
   quote= Quote.find(params[:id])
    quote.destroy
    redirect_to quotes_path
  end

  private

  def get_quote
    @response = Unirest.post "https://andruxnet-random-famous-quotes.p.mashape.com/?cat=movies",
  headers:{
    "X-Mashape-Key" => "OAeeRC5ECumsht9joxbpWmXH8wOsp1W9wK4jsnbgrOqAtlu1fG",
    "Content-Type" => "application/x-www-form-urlencoded",
    "Accept" => "application/json"
  }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/get_quote.html.erb
<%= @response.body %>

app/views/quotes/index.html.erb
<%= button_to "Get new quote", create_quote_path %>

<% @quotes.each do |quote| %>
  <div>
    <%= link_to "Show me the quote!!!", show_quote_path(quote) %>
    <%= button_to "Destroy!", delete_quote_path(quote), method: :delete %>
    <p><%= quote.author %></p>
    <p><%= quote.quote %></p>
    <p><%= quote.category %></p>
  </div>
<% end %>

app/views/quotes/show.html.erb
<p><%= @quote.author %></p>
<p><%= @quote.quote %></p>
<p><%= @quote.category %></p>

app/views/welcome/index.html.erb
gratulacje Kasiunia :)

app/views/welcome/show.html.erb
Super warsztaty 